name: "Create dotenv from AWS SSM"
description: "Get many SSM Parameter Store values ​​from a file to the dotenv file"
branding:
  icon: "cloud"
  color: "blue"
author: "3nu3l"
inputs:
  inputFilename:
    description: "Filename received as parameter or .env.map by default"
  outputFilename:
    description: "Filename received as parameter or .env by default"
runs:
  using: "node24"
  main: "dist/index.js"
